### ISSUE TITLE
Getting same url every time an avatar is build

### ISSUE THREAD

**Issue by julitogtu** [readyplayerme/Example-iframe#10]
Hi, i'm running some test to see the iframe integration in action but every time I run this i'm getting the same avatar url (even in different browsers), I don't know if this happens because I'm using the demo domain and it will be solve if I have with a custom sub domain or if maybe there is something extra needed to have different urls when using it multiple times.

I checked the documentation however, i did not find a solution.

Thanks

**Comment by iiLearner** [comment]
bump?

**Comment by tiivik** [comment]
@julitogtu We export avatars onto the same URL by design – any edits made on the avatars would reflect on the output avatars as well. In some cases it is not desired however and we recently introduced a clearCache parameter helping you to override this behaviour.

For example `https://demo.readyplayer.me/avatar?clearCache=true`
